#!/bin/bash

# flushing the firewall
iptables -F

#* Filter by MAC
# defining a variable that contains the allowed MAC addresses
PERMITTED_MACS="08:00:27:15:b2:ec 08:00:27:15:b2:df 08:00:27:15:b2:ab"

# this host can communicate only with other hosts inside our LAN that have
# a MAC address from this list
# !!! to be able to communicate outside the LAN (e.g. Internet) the MAC
# of the router internal interface should also be allowed
for MAC in $PERMITTED_MACS; do
  iptables -A INPUT -m mac --mac-source $MAC -j ACCEPT
  echo "$MAC permitted"
done

# set POLICY to DROP on INPUT (all other packets are dropped)
iptables -P INPUT DROP

#* ----
#* Match by Data and Time
## See the help: iptables -m time --help

# !!!!! TIME is UTC and not system time

# accepting incoming tcp port 22 (ssh) packets daily ONLY between 8:00-18:00
iptables -A INPUT -p tcp --dport 22 -m time --timestart 8:00 --timestop 18:00 -j ACCEPT
iptables -A INPUT -p tcp --dport 22 -j DROP

# accepting forwarded traffic (this is the Router) to www.ubuntu.com on workdays between 18:00-08:00
iptables -A FORWARD -p tcp --dport 80 -d www.ubuntu.com -m time --weekdays Mon,Tue,Wed,Thu,Fri \
  --timestart 18:00 --timestop 8:00 -j ACCEPT

# packets to www.ubuntu.com are dropped between 8:00 - 18:00 (working hours)
iptables -A FORWARD -p tcp --dport 80 -d www.ubuntu.com -j DROP

#* The Limit Match
# allow only 1 incoming ping (echo-request) per second with a burst of 3
iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/sec --limit-burst 3 -j ACCEPT
# drop packets that were not accepted by the rule above (they are above the limit)
iptables -A INPUT -p icmp --icmp-type echo-request -j DROP

# allow only 5 new incoming connections per second to port 443 (https)
iptables -A INPUT -p tcp --dport 443 --syn -m limit --limit 5/sec -j ACCEPT
iptables -A INPUT -p tcp --dport 443 --syn -j DROP

#* The Recent Match
##** BUILD A DYNAMIC DATABASE OF BANNED IP ADDRESSES**##

## Get help: iptables -m recent --help
# when a packet is coming, it will be checked against this rule and
# if its source ip belongs to the hacker list, the packet will be dropped
# last seen time is updated with another 60 seconds (the source ip address stays in the list for another 60 seconds)
iptables -A INPUT -m recent --name hackers --update --seconds 60 -j DROP

# when the 1st matched packet arrives (tcp/25 between 8:00-10:00 UTC), a list named hacker is created,
# the source ip address of the packet is added to that list and the packet is dropped
iptables -A INPUT -p tcp --dport 25 -m time --timestart 8:00 --timestop 10:00 -m recent --name hackers --set -j DROP

#* Match by Quota
# permit max QUOTA bytes from protocol tcp and port 80 (ROUTED TRAFFIC, we are the ROUTER)
# traffic is generated by a server inside our LAN. This is downloaded traffic by Internet clients from our server.

### EDIT the values below ###
PROTOCOL="tcp"
PORT="80"
#1GB
QUOTA1="1000000000"
#this is the outgoing interface
INT="eth0"
###

###DO NOT EDIT BELOW THIS LINE
iptables -A FORWARD -o $INT -p $PROTOCOL --sport $PORT -m quota --quota $QUOTA1 -j ACCEPT
iptables -A FORWARD -o $INT -p $PROTOCOL --sport $PORT -j DROP

# permit max 100MB of incoming https traffic from the web site with the address 100.0.0.1

### EDIT the values below ###
HTTPS_SERVER="100.0.0.1"
PROTOCOL="tcp"
PORT="443"
#100MB
QUOTA2="100000000"
###

###DO NOT EDIT BELOW THIS LINE
iptables -A INPUT -s $HTTPS_SERVER -p $PROTOCOL --sport $PORT -m quota --quota $QUOTA2 -j ACCEPT
iptables -A INPUT -p $PROTOCOL --sport $PORT -j DROP
